project_id = "sqgwpenihrcdapptyltt"

[functions.process-video]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-transcription]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
