// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqgwpenihrcdapptyltt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZ3dwZW5paHJjZGFwcHR5bHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExOTIxOTksImV4cCI6MjA3Njc2ODE5OX0.e3d6uAxc8qnN7wQxPJa-GMaovashORvUosGi8Zu-uOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});